--1. Thêm tài khoản và nhân viên
INSERT INTO USER_ACCOUNT
    (USERNAME, PASSWORD_HASH, ROLE)
VALUES
    ('admin', 'DEMO_HASH_CHANGE_ME', 'ADMIN');

INSERT INTO USER_ACCOUNT
    (USERNAME, PASSWORD_HASH, ROLE)
VALUES
    ('employee01', 'DEMO_HASH_CHANGE_ME', 'EMPLOYEE');

INSERT INTO EMPLOYEE
    (ACCOUNT_ID, FULL_NAME, PHONE, POSITION)
SELECT ACCOUNT_ID, 'Nguyen Van Admin',
       '0900000001', 'ADMIN'
FROM USER_ACCOUNT
WHERE USERNAME = 'admin';

INSERT INTO EMPLOYEE
    (ACCOUNT_ID, FULL_NAME, PHONE, POSITION)
SELECT ACCOUNT_ID, 'Tran Van A',
       '0900000002', 'EMPLOYEE'
FROM USER_ACCOUNT
WHERE USERNAME = 'employee01';

--2. Thêm khách hàng và loại xe

INSERT INTO CUSTOMER
    (FULL_NAME, PHONE, ADDRESS)
VALUES
    ('Nguyen Van B', '0911111111', 'Ha Noi');

INSERT INTO CUSTOMER
    (FULL_NAME, PHONE, ADDRESS)
VALUES
    ('Tran Thi C', '0922222222', 'Ha Noi');

INSERT INTO VEHICLE_TYPE
    (TYPE_NAME, DESCRIPTION)
VALUES
    ('MOTORBIKE', 'Xe may');

INSERT INTO VEHICLE_TYPE
    (TYPE_NAME, DESCRIPTION)
VALUES
    ('CAR', 'O to');
    
--3. Thêm phương tiện
INSERT INTO VEHICLE (
    CUSTOMER_ID,
    VEHICLE_TYPE_ID,
    LICENSE_PLATE,
    BRAND,
    COLOR
)
SELECT
    c.CUSTOMER_ID,
    vt.VEHICLE_TYPE_ID,
    '29A-12345',
    'Toyota',
    'Trang'
FROM CUSTOMER c
CROSS JOIN VEHICLE_TYPE vt
WHERE c.PHONE = '0911111111'
  AND vt.TYPE_NAME = 'CAR';

INSERT INTO VEHICLE (
    CUSTOMER_ID,
    VEHICLE_TYPE_ID,
    LICENSE_PLATE,
    BRAND,
    COLOR
)
SELECT
    c.CUSTOMER_ID,
    vt.VEHICLE_TYPE_ID,
    '29B-67890',
    'Honda',
    'Den'
FROM CUSTOMER c
CROSS JOIN VEHICLE_TYPE vt
WHERE c.PHONE = '0922222222'
  AND vt.TYPE_NAME = 'MOTORBIKE';
  
  --4. Thêm khu vực và vị trí đỗ
  INSERT INTO PARKING_AREA
    (AREA_NAME, VEHICLE_TYPE_ID, DESCRIPTION)
SELECT
    'Khu A', VEHICLE_TYPE_ID, 'Khu do o to'
FROM VEHICLE_TYPE
WHERE TYPE_NAME = 'CAR';

INSERT INTO PARKING_AREA
    (AREA_NAME, VEHICLE_TYPE_ID, DESCRIPTION)
SELECT
    'Khu B', VEHICLE_TYPE_ID, 'Khu do xe may'
FROM VEHICLE_TYPE
WHERE TYPE_NAME = 'MOTORBIKE';

INSERT INTO PARKING_SLOT
    (AREA_ID, SLOT_CODE)
SELECT AREA_ID, 'A01'
FROM PARKING_AREA
WHERE AREA_NAME = 'Khu A';

INSERT INTO PARKING_SLOT
    (AREA_ID, SLOT_CODE)
SELECT AREA_ID, 'A02'
FROM PARKING_AREA
WHERE AREA_NAME = 'Khu A';

INSERT INTO PARKING_SLOT
    (AREA_ID, SLOT_CODE)
SELECT AREA_ID, 'B01'
FROM PARKING_AREA
WHERE AREA_NAME = 'Khu B';

INSERT INTO PARKING_SLOT
    (AREA_ID, SLOT_CODE)
SELECT AREA_ID, 'B02'
FROM PARKING_AREA
WHERE AREA_NAME = 'Khu B';

--5. Thêm bảng giá

INSERT INTO PRICE_LIST (
    VEHICLE_TYPE_ID,
    PRICE_TYPE,
    AMOUNT,
    EFFECTIVE_FROM
)
SELECT
    VEHICLE_TYPE_ID,
    'HOURLY',
    20000,
    TRUNC(SYSDATE)
FROM VEHICLE_TYPE
WHERE TYPE_NAME = 'CAR';

INSERT INTO PRICE_LIST (
    VEHICLE_TYPE_ID,
    PRICE_TYPE,
    AMOUNT,
    EFFECTIVE_FROM
)
SELECT
    VEHICLE_TYPE_ID,
    'MONTHLY',
    1500000,
    TRUNC(SYSDATE)
FROM VEHICLE_TYPE
WHERE TYPE_NAME = 'CAR';

INSERT INTO PRICE_LIST (
    VEHICLE_TYPE_ID,
    PRICE_TYPE,
    AMOUNT,
    EFFECTIVE_FROM
)
SELECT
    VEHICLE_TYPE_ID,
    'HOURLY',
    5000,
    TRUNC(SYSDATE)
FROM VEHICLE_TYPE
WHERE TYPE_NAME = 'MOTORBIKE';

INSERT INTO PRICE_LIST (
    VEHICLE_TYPE_ID,
    PRICE_TYPE,
    AMOUNT,
    EFFECTIVE_FROM
)
SELECT
    VEHICLE_TYPE_ID,
    'MONTHLY',
    150000,
    TRUNC(SYSDATE)
FROM VEHICLE_TYPE
WHERE TYPE_NAME = 'MOTORBIKE';

COMMIT;
