INSERT INTO USER_ACCOUNT
    (USERNAME, PASSWORD_HASH, ROLE)
VALUES
    ('admin', 'DEMO_HASH_CHANGE_ME', 'ADMIN');

INSERT INTO USER_ACCOUNT
    (USERNAME, PASSWORD_HASH, ROLE)
VALUES
    ('employee01', 'DEMO_HASH_CHANGE_ME', 'EMPLOYEE');

INSERT INTO EMPLOYEE
    (ACCOUNT_ID, FULL_NAME, PHONE, POSITION)
SELECT ACCOUNT_ID, 'Nguyen Van Admin',
       '0900000001', 'ADMIN'
FROM USER_ACCOUNT
WHERE USERNAME = 'admin';

INSERT INTO EMPLOYEE
    (ACCOUNT_ID, FULL_NAME, PHONE, POSITION)
SELECT ACCOUNT_ID, 'Tran Van A',
       '0900000002', 'EMPLOYEE'
FROM USER_ACCOUNT
WHERE USERNAME = 'employee01';

