CREATE TABLE CUSTOMER(
CUSTOMER_ID NUMBER PRIMARY KEY,
FULL_NAME VARCHAR2(100) NOT NULL,
PHONE VARCHAR2(15),
EMAIL VARCHAR2(100),
ADDERRSS VARCHAR2(200)
);


CREATE TABLE VEHICLE_TYPE (
VEHICLE_TYPE_ID NUMBER PRIMARY KEY,
TYPE_NAME VARCHAR2(50) NOT NULL
);
CREATE TABLE PRICE_LIST (
    PRICE_ID NUMBER PRIMARY KEY,            -- Mã bảng giá
    VEHICLE_TYPE_ID NUMBER NOT NULL,        -- Mã loại xe
    PRICE_PER_HOUR NUMBER(12,2) NOT NULL,   -- Giá theo giờ

    CONSTRAINT FK_PRICE_VEHICLE_TYPE
        FOREIGN KEY (VEHICLE_TYPE_ID)
        REFERENCES VEHICLE_TYPE(VEHICLE_TYPE_ID)
);
CREATE TABLE VEHICLE (
    VEHICLE_ID NUMBER PRIMARY KEY,           -- Mã phương tiện
    LICENSE_PLATE VARCHAR2(20) UNIQUE NOT NULL, -- Biển số
    VEHICLE_TYPE_ID NUMBER NOT NULL,        -- Mã loại xe
    CUSTOMER_ID NUMBER NOT NULL,            -- Mã khách hàng
    COLOR VARCHAR2(30),                      -- Màu xe

    CONSTRAINT FK_VEHICLE_TYPE
        FOREIGN KEY (VEHICLE_TYPE_ID)
        REFERENCES VEHICLE_TYPE(VEHICLE_TYPE_ID),

    CONSTRAINT FK_VEHICLE_CUSTOMER
        FOREIGN KEY (CUSTOMER_ID)
        REFERENCES CUSTOMER(CUSTOMER_ID)
);
CREATE TABLE PARKING_AREA (
    AREA_ID NUMBER PRIMARY KEY,              -- Mã khu vực
    AREA_NAME VARCHAR2(100) NOT NULL        -- Tên khu vực
);
CREATE TABLE PARKING_SLOT (
    SLOT_ID NUMBER PRIMARY KEY,              -- Mã vị trí
    AREA_ID NUMBER NOT NULL,                 -- Mã khu vực
    SLOT_NAME VARCHAR2(20) NOT NULL,        -- Tên vị trí
    STATUS VARCHAR2(30) DEFAULT 'AVAILABLE', -- Trạng thái

    CONSTRAINT FK_SLOT_AREA
        FOREIGN KEY (AREA_ID)
        REFERENCES PARKING_AREA(AREA_ID)
);
CREATE TABLE EMPLOYEE (
    EMPLOYEE_ID NUMBER PRIMARY KEY,          -- Mã nhân viên
    FULL_NAME VARCHAR2(100) NOT NULL,        -- Họ tên
    PHONE VARCHAR2(15),                      -- Số điện thoại
    POSITION VARCHAR2(50)                    -- Chức vụ
);
CREATE TABLE PARKING_TICKET (
    TICKET_ID NUMBER PRIMARY KEY,            -- Mã vé
    VEHICLE_ID NUMBER NOT NULL,              -- Xe nào
    SLOT_ID NUMBER NOT NULL,                 -- Đỗ ở vị trí nào
    EMPLOYEE_ID NUMBER NOT NULL,             -- Nhân viên xử lý
    CHECK_IN_TIME DATE NOT NULL,              -- Thời gian vào
    CHECK_OUT_TIME DATE,                      -- Thời gian ra
    STATUS VARCHAR2(30) DEFAULT 'PARKING',   -- Trạng thái

    CONSTRAINT FK_TICKET_VEHICLE
        FOREIGN KEY (VEHICLE_ID)
        REFERENCES VEHICLE(VEHICLE_ID),

    CONSTRAINT FK_TICKET_SLOT
        FOREIGN KEY (SLOT_ID)
        REFERENCES PARKING_SLOT(SLOT_ID),

    CONSTRAINT FK_TICKET_EMPLOYEE
        FOREIGN KEY (EMPLOYEE_ID)
        REFERENCES EMPLOYEE(EMPLOYEE_ID)
);
CREATE TABLE PAYMENT (
    PAYMENT_ID NUMBER PRIMARY KEY,             -- Mã thanh toán
    TICKET_ID NUMBER NOT NULL,                 -- Mã vé
    AMOUNT NUMBER(12,2) NOT NULL,              -- Số tiền
    PAYMENT_TIME DATE DEFAULT SYSDATE,         -- Thời gian thanh toán
    PAYMENT_METHOD VARCHAR2(30),               -- Phương thức thanh toán

    CONSTRAINT FK_PAYMENT_TICKET
        FOREIGN KEY (TICKET_ID)
        REFERENCES PARKING_TICKET(TICKET_ID)
);
SELECT TABLE_NAME
FROM USER_TABLES
ORDER BY TABLE_NAME;

INSERT INTO PAYMENT
(PAYMENT_ID, TICKET_ID, AMOUNT, PAYMENT_TIME, PAYMENT_METHOD)
VALUES
(1, 2, 15000, 
 TO_DATE('2026-09-25 12:00:00', 'YYYY-MM-DD HH24:MI:SS'),
 'CASH');
SELECT * FROM CUSTOMER;

SELECT * FROM VEHICLE_TYPE;

SELECT * FROM PRICE_LIST;

SELECT * FROM VEHICLE;

SELECT * FROM PARKING_AREA;

SELECT * FROM PARKING_SLOT;

SELECT * FROM EMPLOYEE;

SELECT * FROM PARKING_TICKET;

SELECT * FROM PAYMENT;
COMMIT;