CREATE USER SMART_PARK IDENTIFIED BY "123456";

GRANT CREATE SESSION TO SMART_PARK;

GRANT CREATE TABLE TO SMART_PARK;
GRANT CREATE SEQUENCE TO SMART_PARK;
GRANT CREATE VIEW TO SMART_PARK;
GRANT CREATE PROCEDURE TO SMART_PARK;

SELECT USERNAME, ACCOUNT_STATUS FROM DBA_USERS WHERE USERNAME='SMART_PARK';
ALTER USER SMART_PARK QUOTA UNLIMITED ON USERS;
ALTER USER SMART_PARK QUOTA 100M ON USERS;

